spring:
  datasource:
    url: jdbc:h2:mem:loja_db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: True
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  devtools:
    restart:
      enabled: true
      poll-interval: 2s
      quiet-period: 1s
    livereload:
      enabled: true

logging:
  level:
    web: DEBUG
